In [24]:
import pandas as pd
from pandas import Series, DataFrame
from sklearn import preprocessing

test = preprocessing.LabelEncoder()
#to convert into numbers



data= pd.read_csv('train.csv')
frameTrain = DataFrame(data)

[oldName1,oldName2,oldName3,oldName4,oldName5,oldName6,oldName7,oldName8,oldName9] = frameTrain.columns
frameTrain.rename(columns={oldName1: 'Type', oldName2: 'Montant',oldName3: 'NameSource',oldName4: 'SourceB',oldName5: 'SourceA',oldName6: 'NameDest',oldName7: 'DestB',oldName8: 'DestA',oldName9: 'Label'}, inplace=True)
frameTrain.Type = test.fit_transform(frameTrain.Type)
frameTrain.NameSource = test.fit_transform(frameTrain.NameSource)
frameTrain.NameDest = test.fit_transform(frameTrain.NameDest)
print(frameTest[:10])
print("Il y a "+str(len(frameTrain.loc[frameTrain['Label'] == 1]))+" fraudes")
print("Il y a "+str(len(frameTrain.loc[frameTrain['Label'] == 0]))+" opérations correcte")

   Type     Montant  NameSource     SourceB   SourceA  NameDest      DestB  \
0     4  1158070.88        5119  1158070.88      0.00       397       0.00   
1     1    67128.33        5929    67128.33      0.00      6102  623880.13   
2     1   495002.26        3755    25008.00      0.00       873       0.00   
3     4   615954.92         604   615954.92      0.00      4094       0.00   
4     1  8994286.69        3411  8994286.69      0.00      3092       0.00   
5     1   623152.72        4383   623152.72      0.00      2452  847223.26   
6     3    17206.91        6001    90836.00  73629.09      7906       0.00   
7     3    20099.71         210    77758.49  57658.77      7594       0.00   
8     1   220799.50        2777        0.00      0.00      2130  394666.15   
9     1   146729.67        6672   146729.67      0.00      4130       0.00   

        DestA  Label  
0        0.00      1  
1   691008.45      1  
2   495002.26      0  
3        0.00      1  
4  8994286.69      1  
5  

In [25]:
data= pd.read_csv('test.csv')
frameTest = DataFrame(data)
[oldName1,oldName2,oldName3,oldName4,oldName5,oldName6,oldName7,oldName8,oldName9] = frameTest.columns
frameTest.rename(columns={oldName1: 'Type', oldName2: 'Montant',oldName3: 'NameSource',oldName4: 'SourceB',oldName5: 'SourceA',oldName6: 'NameDest',oldName7: 'DestB',oldName8: 'DestA',oldName9: 'Label'}, inplace=True)
frameTest.Type = test.fit_transform(frameTest.Type)
frameTest.NameSource = test.fit_transform(frameTest.NameSource)
frameTest.NameDest = test.fit_transform(frameTest.NameDest)
print(frameTest[:10])
print("Il y a "+str(len(frameTest.loc[frameTest['Label'] == 1]))+" fraudes")
print("Il y a "+str(len(frameTest.loc[frameTest['Label'] == 0]))+" opérations correcte")

   Type     Montant  NameSource     SourceB   SourceA  NameDest      DestB  \
0     4  1158070.88        5119  1158070.88      0.00       397       0.00   
1     1    67128.33        5929    67128.33      0.00      6102  623880.13   
2     1   495002.26        3755    25008.00      0.00       873       0.00   
3     4   615954.92         604   615954.92      0.00      4094       0.00   
4     1  8994286.69        3411  8994286.69      0.00      3092       0.00   
5     1   623152.72        4383   623152.72      0.00      2452  847223.26   
6     3    17206.91        6001    90836.00  73629.09      7906       0.00   
7     3    20099.71         210    77758.49  57658.77      7594       0.00   
8     1   220799.50        2777        0.00      0.00      2130  394666.15   
9     1   146729.67        6672   146729.67      0.00      4130       0.00   

        DestA  Label  
0        0.00      1  
1   691008.45      1  
2   495002.26      0  
3        0.00      1  
4  8994286.69      1  
5  

In [6]:
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import recall_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_recall_fscore_support

#On test sans les string converties pour le modèle linéaire et le réseau de neuronne
model = SVC(kernel='linear',random_state=0);
modelN = MLPClassifier(random_state=0)


X_train = frameTrain[['Montant','SourceB','SourceA','DestB','DestA']][:2000]
y_train = frameTrain['Label'][:2000]
X_test = frameTest[['Montant','SourceB','SourceA','DestB','DestA']][:2000]
y_test = frameTest['Label'][:2000]

model.fit(X_train,y_train)
modelN.fit(X_train,y_train)
print(model.score(X_train,y_train))
print(model.score(X_test,y_test))
print(modelN.score(X_train,y_train))
print(modelN.score(X_test,y_test))

X_predict = model.predict(X_test)
print(recall_score(y_test,X_predict))
tn, fp, fn, tp = confusion_matrix(y_test,X_predict).ravel()
print((tn, fp, fn, tp))
print(precision_recall_fscore_support(y_test,X_predict))

X_predict = modelN.predict(X_test)
print(recall_score(y_test,X_predict))
tn, fp, fn, tp = confusion_matrix(y_test,X_predict).ravel()
print((tn, fp, fn, tp))
print(precision_recall_fscore_support(y_test,X_predict))

1.0
0.751
0.9995
0.5065
0.495440729483
(1013, 0, 498, 489)
(array([ 0.67041694,  1.        ]), array([ 1.        ,  0.49544073]), array([ 0.80269414,  0.66260163]), array([1013,  987]))
0.0
(1013, 0, 987, 0)
(array([ 0.5065,  0.    ]), array([ 1.,  0.]), array([ 0.67241952,  0.        ]), array([1013,  987]))


/usr/local/lib/python3.5/dist-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [7]:
from sklearn import tree


model = tree.DecisionTreeClassifier(random_state=0)

X_train = frameTrain[['Type','Montant','NameSource','SourceB','SourceA','NameDest','DestB','DestA']]
y_train = frameTrain['Label']
X_test = frameTest[['Type','Montant','NameSource','SourceB','SourceA','NameDest','DestB','DestA']]
y_test = frameTest['Label']

model.fit(X_train,y_train)
print(model.score(X_train,y_train))
print(model.score(X_test,y_test))

X_predict = model.predict(X_test)
print(recall_score(y_test,X_predict))
tn, fp, fn, tp = confusion_matrix(y_test,X_predict).ravel()
print((tn, fp, fn, tp))
print(precision_recall_fscore_support(y_test,X_predict))


1.0
0.922240280035
0.844883662747
(4000, 2, 620, 3377)
(array([ 0.86580087,  0.99940811]), array([ 0.99950025,  0.84488366]), array([ 0.92785897,  0.91567245]), array([4002, 3997]))


In [8]:
from sklearn.decomposition import PCA
pca = PCA(n_components=8,random_state=0)
X_train = frameTrain[['Type','Montant','NameSource','SourceB','SourceA','NameDest','DestB','DestA']]
y_train = frameTrain['Label']
X_test = frameTest[['Type','Montant','NameSource','SourceB','SourceA','NameDest','DestB','DestA']]
y_test = frameTest['Label']
pca.fit(X_train)
X_pca_train = pca.transform(X_train)
X_pca_test = pca.transform(X_test)


In [9]:
model = tree.DecisionTreeClassifier(random_state=0)


X_train = frameTrain[['Type','Montant','SourceB','SourceA','DestB','DestA']]
y_train = frameTrain['Label']
X_test = frameTest[['Type','Montant','SourceB','SourceA','DestB','DestA']]
y_test = frameTest['Label']

model.fit(X_train,y_train)
print(model.score(X_train,y_train))
print(model.score(X_test,y_test))


1.0
0.93186648331


In [10]:
X_predict = model.predict(X_test)
print(recall_score(y_test,X_predict))
tn, fp, fn, tp = confusion_matrix(y_test,X_predict).ravel()
print((tn, fp, fn, tp))
print(precision_recall_fscore_support(y_test,X_predict))

0.863897923443
(4001, 1, 544, 3453)
(array([ 0.88030803,  0.99971048]), array([ 0.99975012,  0.86389792]), array([ 0.93623494,  0.92685546]), array([4002, 3997]))


In [11]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators = 10,random_state=0)


X_train = frameTrain[['Type','Montant','SourceB','SourceA','DestB','DestA']]
y_train = frameTrain['Label']
X_test = frameTest[['Type','Montant','SourceB','SourceA','DestB','DestA']]
y_test = frameTest['Label']

model.fit(X_train,y_train)
print(model.score(X_train,y_train))
print(model.score(X_test,y_test))

0.999933999967
0.877359669959


In [12]:
X_predict = model.predict(X_test)
print(recall_score(y_test,X_predict))
tn, fp, fn, tp = confusion_matrix(y_test,X_predict).ravel()
print((tn, fp, fn, tp))
print(precision_recall_fscore_support(y_test,X_predict))

0.754565924443
(4002, 0, 981, 3016)
(array([ 0.80313064,  1.        ]), array([ 1.        ,  0.75456592]), array([ 0.89081803,  0.86011693]), array([4002, 3997]))


In [13]:
import pandas as pd
from pandas import Series, DataFrame
from sklearn import preprocessing
from sklearn import tree

test = preprocessing.LabelEncoder()
#to convert into numbers



data= pd.read_csv('train.csv')
frameTrain = DataFrame(data)

[oldName1,oldName2,oldName3,oldName4,oldName5,oldName6,oldName7,oldName8,oldName9] = frameTrain.columns
frameTrain.rename(columns={oldName1: 'Type', oldName2: 'Montant',oldName3: 'NameSource',oldName4: 'SourceB',oldName5: 'SourceA',oldName6: 'NameDest',oldName7: 'DestB',oldName8: 'DestA',oldName9: 'Label'}, inplace=True)
frameTrain.Type = test.fit_transform(frameTrain.Type)
frameTrain.NameSource = test.fit_transform(frameTrain.NameSource)
frameTrain.NameDest = test.fit_transform(frameTrain.NameDest)
print("training set imported")

data= pd.read_csv('predict.csv')
framePredict = DataFrame(data)

[oldName1,oldName2,oldName3,oldName4,oldName5,oldName6,oldName7,oldName8] = framePredict.columns
framePredict.rename(columns={oldName1: 'Type', oldName2: 'Montant',oldName3: 'NameSource',oldName4: 'SourceB',oldName5: 'SourceA',oldName6: 'NameDest',oldName7: 'DestB',oldName8: 'DestA'}, inplace=True)
framePredict.Type = test.fit_transform(framePredict.Type)
framePredict.NameSource = test.fit_transform(framePredict.NameSource)
framePredict.NameDest = test.fit_transform(framePredict.NameDest)
print("training set imported")

model = tree.DecisionTreeClassifier(random_state=0)


X_train = frameTrain[['Type','Montant','SourceB','SourceA','DestB','DestA']]
y_train = frameTrain['Label']
X_test = framePredict[['Type','Montant','SourceB','SourceA','DestB','DestA']]

model.fit(X_train,y_train)
print("model trained")

X_predict = model.predict(X_test)
print("model predicted")
.Series(np.random.randn(sLength), index=df1.index)

training set imported
training set imported
model trained
model predicted


In [15]:
framePredict['Label'] = X_predict
framePredict


Type      Montant  NameSource      SourceB      SourceA  NameDest  \
0        4    290211.26        1311    290211.26         0.00      1334   
1        4    178344.25         327    178344.25         0.00      1212   
2        1   1023189.90          65   1023189.90         0.00      1158   
3        4    592615.53        1395    592615.53         0.00       383   
4        3      2632.63         920         0.00         0.00      1800   
5        0     60402.09         152   3130888.26   3191290.35        52   
6        1    152097.84        1066         0.00         0.00       831   
7        0    251107.86        1280    398483.00    649590.86      1663   
8        1     75734.99         101     75734.99         0.00       892   
9        4       493.28         789       493.28         0.00       500   
10       3     34185.61         574      7253.00         0.00      1901   
11       1    451399.66         573    451399.66         0.00      1299   
12       1    371020.35         659    121994.00         0.00      1623   
13       1    207261.07         937    207261.07         0.00       787   
14       4   1467987.57        1124   1467987.57         0.00       300   
15       4   1212259.76        1396         0.00         0.00       679   
16       4     19421.77        1517     19421.77         0.00       788   
17       1    844213.81         941    844213.81         0.00      1296   
18       1    238188.01        1260     68284.00         0.00      1659   
19       1    236914.77         460    236914.77         0.00      1185   
20       4  10000000.00        1425  31343002.08  21343002.08      1303   
21       4    342988.79         589    342988.79         0.00      1261   
22       3     10124.39        1728         0.00         0.00      1746   
23       1     93561.29         404       909.00         0.00      1297   
24       1     50523.78         771     50523.78         0.00       149   
25       4   1889351.63         648   1889351.63         0.00        47   
26       3     36505.02         167         0.00         0.00      1767   
27       4     22117.99        1880     22117.99         0.00       846   
28       4    677503.25         505    677503.25         0.00       591   
29       1   2562459.56         504   2562459.56         0.00       870   
...    ...          ...         ...          ...          ...       ...   
1969     0    154313.42         150        63.00    154376.42      1280   
1970     4    106681.18         955    106681.18         0.00       627   
1971     4   5239429.19         579   5239429.19         0.00       680   
1972     4    117683.42        1488    117683.42         0.00      1662   
1973     0     44547.46        1539   6244178.66   6288726.11        90   
1974     1   1340263.67         541   1340263.67         0.00       522   
1975     3     16201.13         900         0.00         0.00      1775   
1976     1    131312.41        1349         0.00         0.00      1248   
1977     1     89809.91        1144         0.00         0.00        53   
1978     3     21782.10         584     15985.71         0.00      1883   
1979     1  10000000.00        1202  10000000.00         0.00       744   
1980     1     49388.66         782     42225.00         0.00       282   
1981     3      6177.50        1814         0.00         0.00      1799   
1982     4    834592.40         441    834592.40         0.00       294   
1983     1    261459.81         818         0.00         0.00        19   
1984     1    181224.98          98    181224.98         0.00       999   
1985     0    139285.79         639         0.00    139285.79       153   
1986     1    326250.51         657    326250.51         0.00      1153   
1987     4    564263.94        1667    564263.94         0.00       434   
1988     1   7596886.83        1032   7596886.83         0.00       669   
1989     1    145944.80         410    145944.80         0.00      1043   
1990     3     22638.85        